broadcast:
  kit-load: true
  kit-load-message: "&#7cff6e%player% loaded %kit%."
  kitroom-open: true
  kitroom-open-message: "&#7cff6e%player% opened the Virtual Kit Room."
  premadekit-load: true
  premadekit-load-message: "&#7cff6e%player% loaded the premade kit."


messages:
  no-permission: "&#ffa6a6You do not have permission to use this command."
  blacklisted-region: "&#ffa6a6You cannot use this command here."
  kit-saved: "&#7cff6e%kit% saved successfully!"
  kit-loaded: "&#7cff6e%kit% loaded successfully!"
  enderchest-saved: "&#7cff6eEnder chest for %kit% saved successfully!"
  premade-kit-saved: "&#7cff6ePremade kit saved successfully!"
  premade-kit-loaded: "&#7cff6ePremade kit loaded successfully!"
  premade-kit-empty: "&#ffa6a6The premade kit is empty."

blacklisted-regions:
  - swordffa
  - netheritepotion