name: KitsX
version: '1.0.0'
main: dev.darkxx.kitsx.KitsX
api-version: '1.19'
authors:
  - Darkxx
  - XyrisPlugins
softdepend:
  - WorldGuard
  - Skript
description: A modern kits plugin for the Crystal PvP server.
website: https://xyris.fun/

permissions:
  kitsx.admin:
    default: op
  kitsx.autokit:
    default: op